### ISSUE TITLE
Multiple params in query string in URL

### ISSUE THREAD

**Issue by conymaniac** [seznam/IMA.js-core#59]
If there are multiple params in query string in URL, the router parses params and set only the last value.

**Comment by jurca** [comment]
This is expected behavior. There is no definitive standard as to what is and what is not permitted in the URL's query string, the specs say that this is scheme-specific. Various servers have implemented various approachs to handling repeated query parameter names, the IMA.js currently mimics the behavior of the Express.JS framework.

See: https://en.wikipedia.org/wiki/Query_string#Web_forms

That being said, it should be possible to access all the data passed by the client. The steps to resolve this issue will be as follows:
1. deprecate the `AbstractController`'s params `field`
2. introduce a new field in the `AbstractController` class named `parameters`
3. the `parameters` field will be a wrapper object for manipulating the data provided by the client.

The parameters accessor object will provide the following methods:
* `get(name: string): ?string` - returns the last value specified by the client of the specified parameter (just like accessing the value through the legacy params object). Returns `null` if the parameter is not specified. The method also accesses the route parameters.
* `getRouteParam(name: string): ?string` - returns the value of the specified route parameter without checking the query parameters and/or request body
* `getAll(name: string): ?string[]` - returns all values of the specified parameter as specified by the client in the same order. Returns `null` if the parameter does not exist. Does not include the route parameter value if the parameter is overridden in the query or request body. The query/request body parameters specified without the value separator (`=`) will have `null` as its value to distinguish between `foo=` and `foo` in the query string/request body.

**Comment by mjancarik** [comment]
Or you may use manually method split and join for defining multiple value for field.

**Comment by mjancarik** [comment]
Because in web has not standard for this. So IMA.js will not solve this for you. You have opportunity to make that how you want.
